import type { D1Migration } from '@cloudflare/vitest-pool-workers';

// `env` from cloudflare:test is typed as Cloudflare.Env (generated by `wrangler types`); the tests add
// the migrations binding that vitest.config.ts injects.
declare global {
  namespace Cloudflare {
    interface Env {
      TEST_MIGRATIONS: D1Migration[];
    }
  }
}

export {};
